name: unmei_fl
description: Nonel App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cookie_manager: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0
  cookie_jar: ^3.0.0
  dio: ^4.0.0
  http: ^0.13.3
  path_provider: ^2.0.1
  connectivity_plus: ^1.0.0

  url_launcher: ^6.0.3
  shimmer: ^2.0.0
#  cached_network_image: ^3.0.0
  persistent_bottom_nav_bar: ^3.1.0

#  flutter_riverpod: ^0.14.0+3

  redux: ^5.0.0
  redux_thunk: ^0.4.0
  flutter_redux: ^0.8.2
  redux_persist_flutter: ^0.9.0

  fluttertoast: ^8.0.8
  flutter_svg: ^0.21.0-nullsafety.0
  adaptive_theme: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  custom_refresh_indicator: ^1.0.0

  syncfusion_flutter_core: ^19.1.55
  syncfusion_flutter_charts: ^19.1.55+1

  intl: ^0.17.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  image_path_ios: 'assets/images/favicon.png'
#  image_path_android: 'assets/images/favicon.png'
#  android: true
#  ios: true

flutter_launcher_icons:
    path: ../

flutter_icons:
  image_path_ios: 'assets/images/favicon.png'
  image_path_android: 'assets/images/favicon.png'
  adaptive_icon_background: 'assets/images/favicon.png'
  adaptive_icon_foreground: 'assets/images/favicon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/platform/